name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare version
        uses: actions/github-script@v6
        with:
          script: |
            const script = require(require('path').resolve('./.github/workflows/version.js'))
            const vs = script({ context, github, firstRev: 'c7a644fe' });
            const verStr = vs.formatVersion(`1.$(GitRevCount)-$(GitBranch) ($(GitSha6)/$(yyyy)-$(mm)-$(dd))`).replace('-main', '');
            const verNum = vs.formatVersion(`1.$(GitRevCount)`);
            core.exportVariable('VER_STR', verStr);
            core.exportVariable('VER_NUM', verNum);
            vs.updateText('Src/Program.cs', 'Version [dev]', `Version ${verStr}`);

      - name: Install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: dotnet restore
        run: dotnet restore

      - name: "dotnet publish: ${{ env.VER_STR }}"
        run: dotnet publish Src\RemoveEmptyDirs.csproj --configuration Release -p:InformationalVersion="${{env.VER_STR}}" -p:Version=${{env.VER_NUM}} -p:FileVersion=${{env.VER_NUM}} -p:AssemblyVersion=${{env.VER_NUM}} -o Publish

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: RemoveEmptyDirs-v${{env.VER_NUM}}
          path: Publish
          if-no-files-found: error
